Repository PIC-IRIS/PH5, pull requests merged in 2018-05, with the labels that each got.

#196 Utilities for converting kef to csv and back.
  CHANGELOG.txt
  ph5/utilities/csvtokef.py
  ph5/utilities/keftocsv.py
  setup.py
Labels: enhancement, in progress

#200 Update ph5torec.py
  ph5/clients/ph5torec.py
Labels: bug

#201 Ph5 validate
  ph5/CONTRIBUTORS.txt
  ph5/utilities/ph5validate.py
Labels: enhancement
