Repository PIC-IRIS/PH5, pull requests merged in 2019-02, with the labels that each got.

#260 Ph5toms change to make day volumes
  CHANGELOG.txt
  ph5/clients/ph5toms.py
  ph5/core/ph5utils.py
Labels: enhancement

#268 Fixes #264
  CHANGELOG.txt
  ph5/clients/ph5toms.py
Labels: bug

#269 Helpfile
  CHANGELOG.txt
  ph5/CONTRIBUTORS.txt
  ph5/core/columns.py
  ph5/utilities/ph5_help.py
  setup.py
Labels: enhancement

#272 pforma processes
  ph5/utilities/pforma_io.py
Labels: enhancement

#271 fixes #270
  CHANGELOG.txt
  ph5/utilities/dumpfair.py
Labels: bug

#274 fixes seg2toph5
  CHANGELOG.txt
  ph5/utilities/125a2ph5.py
  ph5/utilities/1302ph5.py
  ph5/utilities/pforma_io.py
  ph5/utilities/seg2toph5.py
Labels: bug, enhancement
