Repository PIC-IRIS/PH5, pull requests merged in 2019-01, with the labels that each got.

#238 Address error #231
  ph5/clients/ph5toms.py
  ph5/clients/ph5view/ph5_viewer.py
  ph5/core/experiment.py
  ph5/core/kef.py
  ph5/core/kefx.py
  ph5/core/pmonitor.py
  ph5/core/pn130.py
  ph5/core/segyreader.py
  ph5/utilities/125a2ph5.py
  ph5/utilities/1302ph5.py
  ph5/utilities/dumpsgy.py
  ph5/utilities/grao2ph5.py
  ph5/utilities/kef2kml.py
  ph5/utilities/load_das_t.py
  ph5/utilities/novenqc.py
  ph5/utilities/novitiate.py
  ph5/utilities/pforma_io.py
  ph5/utilities/pformagui.py
  ph5/utilities/ph5_merge_helper.py
  ph5/utilities/report2ph5.py
  ph5/utilities/seg2toph5.py
  ph5/utilities/segd2ph5.py
  ph5/utilities/set_n_i_response.py
  ph5/utilities/time_kef_gen.py
Labels: bug, enhancement

#242 fix test_ph5toms
  CHANGELOG.txt
  ph5/clients/tests/test_ph5toms.py
Labels: bug

#244 Clarify UTM zone designations in pforma and segdtoph5
  ph5/utilities/pformagui.py
  ph5/utilities/segd2ph5.py
Labels: enhancement

#227 Improve the way setup.py handles c_dependencies
  CHANGELOG.txt
  ph5/clients/ph5view/ph5_viewer.py
  ph5/core/c_dependencies/subcd_py.py
  ph5/core/c_dependencies/sufirfilt_py.py
  ph5/core/c_dependencies/suibm2ieee_py.py
  ph5/core/c_dependencies/surt_125a_py.py
  ph5/core/c_dependencies/surt_130_py.py
  ph5/core/pmonitor.py
  ph5/utilities/changes.py
  ph5/utilities/kefedit.py
  ph5/utilities/noven.py
  ph5/utilities/novitiate.py
  ph5/utilities/pformagui.py
  setup.py
Labels: enhancement

#249 fixes issue #221 RESP import error
  ph5/clients/ph5toevt.py
  ph5/clients/ph5torec.py
  ph5/utilities/resp_load.py
  ph5/utilities/seg2toph5.py
Labels: bug

#248 segd2ph5 read correct channel sets
  ph5/utilities/segd2ph5.py
Labels: bug

#254 More ph5_validate enhancements
  ph5/utilities/ph5validate.py
Labels: enhancement

#252 fixes #229
  CHANGELOG.txt
  ph5/clients/ph5tostationxml.py
  ph5/clients/ph5view/ph5_viewer.py
  ph5/core/ph5api.py
  ph5/utilities/ph5validate.py
Labels: enhancement

#258 Return empty response element in StationXML if a response was not loaded into PH5
  ph5/clients/ph5tostationxml.py
Labels: bug
